"""initial

Revision ID: 3cc22f16ed1f
Revises: 
Create Date: 2026-06-18 09:38:36.613981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc22f16ed1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('attempted_event_id', sa.String(), nullable=False),
    sa.Column('attempted_payload_hash', sa.String(), nullable=False),
    sa.Column('existing_event_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_idempotency_key'), 'conflicts', ['idempotency_key'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('related_entity_ids', sa.JSON(), nullable=False),
    sa.Column('reliability', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('raw_body', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('processed_keys',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_keys')
    op.drop_table('events')
    op.drop_index(op.f('ix_conflicts_idempotency_key'), table_name='conflicts')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
